package com.playfab
{
	import flash.utils.Dictionary;

	public class PlayFabError
	{
		public static const Unknown:int = 1;
		public static const NetworkIOError:int = 2;
		public static const FlashSecurityError:int = 3;

		public static const Success:int = 0;
		public static const InvalidParams:int = 1000;
		public static const AccountNotFound:int = 1001;
		public static const AccountBanned:int = 1002;
		public static const InvalidUsernameOrPassword:int = 1003;
		public static const InvalidTitleId:int = 1004;
		public static const InvalidEmailAddress:int = 1005;
		public static const EmailAddressNotAvailable:int = 1006;
		public static const InvalidUsername:int = 1007;
		public static const InvalidPassword:int = 1008;
		public static const UsernameNotAvailable:int = 1009;
		public static const InvalidSteamTicket:int = 1010;
		public static const AccountAlreadyLinked:int = 1011;
		public static const LinkedAccountAlreadyClaimed:int = 1012;
		public static const InvalidFacebookToken:int = 1013;
		public static const AccountNotLinked:int = 1014;
		public static const FailedByPaymentProvider:int = 1015;
		public static const CouponCodeNotFound:int = 1016;
		public static const InvalidContainerItem:int = 1017;
		public static const ContainerNotOwned:int = 1018;
		public static const KeyNotOwned:int = 1019;
		public static const InvalidItemIdInTable:int = 1020;
		public static const InvalidReceipt:int = 1021;
		public static const ReceiptAlreadyUsed:int = 1022;
		public static const ReceiptCancelled:int = 1023;
		public static const GameNotFound:int = 1024;
		public static const GameModeNotFound:int = 1025;
		public static const InvalidGoogleToken:int = 1026;
		public static const UserIsNotPartOfDeveloper:int = 1027;
		public static const InvalidTitleForDeveloper:int = 1028;
		public static const TitleNameConflicts:int = 1029;
		public static const UserisNotValid:int = 1030;
		public static const ValueAlreadyExists:int = 1031;
		public static const BuildNotFound:int = 1032;
		public static const PlayerNotInGame:int = 1033;
		public static const InvalidTicket:int = 1034;
		public static const InvalidDeveloper:int = 1035;
		public static const InvalidOrderInfo:int = 1036;
		public static const RegistrationIncomplete:int = 1037;
		public static const InvalidPlatform:int = 1038;
		public static const UnknownError:int = 1039;
		public static const SteamApplicationNotOwned:int = 1040;
		public static const WrongSteamAccount:int = 1041;
		public static const TitleNotActivated:int = 1042;
		public static const RegistrationSessionNotFound:int = 1043;
		public static const NoSuchMod:int = 1044;
		public static const FileNotFound:int = 1045;
		public static const DuplicateEmail:int = 1046;
		public static const ItemNotFound:int = 1047;
		public static const ItemNotOwned:int = 1048;
		public static const ItemNotRecycleable:int = 1049;
		public static const ItemNotAffordable:int = 1050;
		public static const InvalidVirtualCurrency:int = 1051;
		public static const WrongVirtualCurrency:int = 1052;
		public static const WrongPrice:int = 1053;
		public static const NonPositiveValue:int = 1054;
		public static const InvalidRegion:int = 1055;
		public static const RegionAtCapacity:int = 1056;
		public static const ServerFailedToStart:int = 1057;
		public static const NameNotAvailable:int = 1058;
		public static const InsufficientFunds:int = 1059;
		public static const InvalidDeviceID:int = 1060;
		public static const InvalidPushNotificationToken:int = 1061;
		public static const NoRemainingUses:int = 1062;
		public static const InvalidPaymentProvider:int = 1063;
		public static const PurchaseInitializationFailure:int = 1064;
		public static const DuplicateUsername:int = 1065;
		public static const InvalidBuyerInfo:int = 1066;
		public static const NoGameModeParamsSet:int = 1067;
		public static const BodyTooLarge:int = 1068;
		public static const ReservedWordInBody:int = 1069;
		public static const InvalidTypeInBody:int = 1070;
		public static const InvalidRequest:int = 1071;
		public static const ReservedEventName:int = 1072;
		public static const InvalidUserStatistics:int = 1073;
		public static const NotAuthenticated:int = 1074;
		public static const StreamAlreadyExists:int = 1075;
		public static const ErrorCreatingStream:int = 1076;
		public static const StreamNotFound:int = 1077;
		public static const InvalidAccount:int = 1078;
		public static const PurchaseDoesNotExist:int = 1080;
		public static const InvalidPurchaseTransactionStatus:int = 1081;
		public static const APINotEnabledForGameClientAccess:int = 1082;
		public static const NoPushNotificationARNForTitle:int = 1083;
		public static const BuildAlreadyExists:int = 1084;
		public static const BuildPackageDoesNotExist:int = 1085;
		public static const CustomAnalyticsEventsNotEnabledForTitle:int = 1087;
		public static const InvalidSharedGroupId:int = 1088;
		public static const NotAuthorized:int = 1089;
		public static const MissingTitleGoogleProperties:int = 1090;
		public static const InvalidItemProperties:int = 1091;
		public static const InvalidPSNAuthCode:int = 1092;
		public static const InvalidItemId:int = 1093;
		public static const PushNotEnabledForAccount:int = 1094;
		public static const PushServiceError:int = 1095;
		public static const ReceiptDoesNotContainInAppItems:int = 1096;
		public static const ReceiptContainsMultipleInAppItems:int = 1097;
		public static const InvalidBundleID:int = 1098;
		public static const JavascriptException:int = 1099;
		public static const InvalidSessionTicket:int = 1100;
		public static const UnableToConnectToDatabase:int = 1101;
		public static const InternalServerError:int = 1110;
		public static const InvalidReportDate:int = 1111;
		public static const ReportNotAvailable:int = 1112;
		public static const DatabaseThroughputExceeded:int = 1113;
		public static const InvalidLobbyId:int = 1114;
		public static const InvalidGameTicket:int = 1115;
		public static const ExpiredGameTicket:int = 1116;
		public static const GameTicketDoesNotMatchLobby:int = 1117;
		public static const LinkedDeviceAlreadyClaimed:int = 1118;
		public static const DeviceAlreadyLinked:int = 1119;
		public static const DeviceNotLinked:int = 1120;
		public static const PartialFailure:int = 1121;
		public static const PublisherNotSet:int = 1122;
		public static const ServiceUnavailable:int = 1123;
		public static const VersionNotFound:int = 1124;
		public static const RevisionNotFound:int = 1125;
		public static const InvalidPublisherId:int = 1126;
		public static const DownstreamServiceUnavailable:int = 1127;
		public static const APINotIncludedInTitleUsageTier:int = 1128;
		public static const DAULimitExceeded:int = 1129;
		public static const APIRequestLimitExceeded:int = 1130;
		public static const InvalidAPIEndpoint:int = 1131;
		public static const BuildNotAvailable:int = 1132;
		public static const ConcurrentEditError:int = 1133;
		public static const ContentNotFound:int = 1134;
		public static const CharacterNotFound:int = 1135;
		public static const CloudScriptNotFound:int = 1136;
		public static const ContentQuotaExceeded:int = 1137;
		public static const InvalidCharacterStatistics:int = 1138;
		public static const PhotonNotEnabledForTitle:int = 1139;
		public static const PhotonApplicationNotFound:int = 1140;
		public static const PhotonApplicationNotAssociatedWithTitle:int = 1141;


		public function PlayFabError(data:Object=null)
		{
			if(data == null) return;
			HttpCode = data.HttpCode;
			HttpStatus = data.HttpStatus;
			Error = data.Error;
			ErrorMessage = data.ErrorMessage;
			ErrorDetails = data.ErrorDetails;
		}
		
		public var HttpCode:int;
		public var HttpStatus:String;
		public var Error:int;
		public var ErrorMessage:String;
		public var ErrorDetails:Dictionary;
	}
}